### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by immrakpk** [grochadc/reddit-tumblr-bot#1]
c:\Users\Rehan\Desktop\stuff\reddit-tumblr-bot\bot\index.js:30
        config.tumblr.tags
              ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by grochadc** [comment]
[From commit comment](https://github.com/grochadc/reddit-tumblr-bot/commit/9ca6621f5fede5837105603e19b82769d8e21fa8#commitcomment-32642764) by @immrakpk
> A comma in bot-config-example.js is missing at the end of tags (i.e. it should be tags:"tag1,tag2",). But still the bot is not working. I dont know if its my node version v10.15.3.

Thanks for pointing it out. I have updated the code to reflect this.

**Comment by grochadc** [comment]
[From comment on commit ](https://github.com/grochadc/reddit-tumblr-bot/commit/9ca6621f5fede5837105603e19b82769d8e21fa8#commitcomment-32642850) by @immrakpk 
> So,
> tumblr.post({
> caption: `<a href="http://reddit.com/${link.permalink}"> ${ link.title }</a>`,
> **data64**: image,
> **blogName**: config.tumblr.blog,
> config.tumblr.tags
> });
> I think the problem is config.tumblr.tags is not associated with a keyword like config.tumblr.blog is associated with blogName. But I still dont know what keyword you have used in other files to map that attribute.

You are absolutely correct. The argument for `Tumblr.post()` should be a correctly structured object. Here it was missing a key; In this case it should be `tags: config.tumblr.tags`. 
I guess my linter wasn`t working correctly and missed this. 

I fixed this issue in the [last commit ](https://github.com/grochadc/reddit-tumblr-bot/commit/42395a2b06e43b7aa13460e21917ac171453a7cb)

Pull from the master repo and try again. If it works tell me to close this issue (or close it yourself).
